FROM python:3.12-slim

WORKDIR /app

COPY index.html ./index.html
COPY server.py ./server.py
COPY README.html ./README.html
COPY README.md ./README.md
COPY README.pdf ./README.pdf
COPY DEPLOY_SYNOLOGY_JA.html ./DEPLOY_SYNOLOGY_JA.html
COPY DEPLOY_SYNOLOGY_JA.md ./DEPLOY_SYNOLOGY_JA.md
COPY DEPLOY_SYNOLOGY_JA.pdf ./DEPLOY_SYNOLOGY_JA.pdf
COPY OPERATIONS_MANUAL_PDF_JA.html ./OPERATIONS_MANUAL_PDF_JA.html
COPY OPERATIONS_MANUAL_JA.md ./OPERATIONS_MANUAL_JA.md
COPY OPERATIONS_MANUAL_JA.pdf ./OPERATIONS_MANUAL_JA.pdf
COPY TAILSCALE_CLIENT_GUIDE_JA.html ./TAILSCALE_CLIENT_GUIDE_JA.html
COPY TAILSCALE_CLIENT_GUIDE_JA.md ./TAILSCALE_CLIENT_GUIDE_JA.md
COPY TAILSCALE_CLIENT_GUIDE_JA.pdf ./TAILSCALE_CLIENT_GUIDE_JA.pdf
COPY TAILSCALE_TABLET_GUIDE_JA.html ./TAILSCALE_TABLET_GUIDE_JA.html
COPY TAILSCALE_TABLET_GUIDE_JA.md ./TAILSCALE_TABLET_GUIDE_JA.md
COPY TAILSCALE_TABLET_GUIDE_JA.pdf ./TAILSCALE_TABLET_GUIDE_JA.pdf
COPY TAILSCALE_TABLET_MESSAGE_TEMPLATE_JA.html ./TAILSCALE_TABLET_MESSAGE_TEMPLATE_JA.html
COPY TAILSCALE_TABLET_MESSAGE_TEMPLATE_JA.md ./TAILSCALE_TABLET_MESSAGE_TEMPLATE_JA.md
COPY TAILSCALE_TABLET_MESSAGE_TEMPLATE_JA.pdf ./TAILSCALE_TABLET_MESSAGE_TEMPLATE_JA.pdf
COPY TAILSCALE_TABLET_QR_SHEET_JA.html ./TAILSCALE_TABLET_QR_SHEET_JA.html
COPY TAILSCALE_TABLET_QR_SHEET_JA.md ./TAILSCALE_TABLET_QR_SHEET_JA.md
COPY TAILSCALE_TABLET_QR_SHEET_JA.pdf ./TAILSCALE_TABLET_QR_SHEET_JA.pdf
COPY TailscaleClientLauncher.cmd ./TailscaleClientLauncher.cmd
COPY TailscaleClientLauncher.ps1 ./TailscaleClientLauncher.ps1
COPY TailscaleClientLauncher.settings.json ./TailscaleClientLauncher.settings.json
COPY .env.example ./.env.example
COPY assets ./assets

EXPOSE 8010
VOLUME ["/data"]

ENV KOUKU_KINOU_DB=/data/records.db

CMD ["python", "server.py", "--host", "0.0.0.0", "--port", "8010", "--db", "/data/records.db"]